export type { SiteVersion, ScrapeStrategy } from './types.js'
export { detectSiteVersion } from './detect.js'
export { classicStrategy } from './classic.js'
export { ariStrategy, parseAriUrl } from './ari.js'
export { bigsplashStrategy, parseBigsplashMetaStrip, parseBigsplashTitle } from './bigsplash.js'
