import { pgTable, text, timestamp, uuid, jsonb, boolean } from 'drizzle-orm/pg-core'

export const dealers = pgTable('dealers', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  logo: text('logo'),
  phone: text('phone'),
  email: text('email'),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  zip: text('zip'),
  hours: text('hours'),
  heroImage: text('hero_image'),
  heroTitle: text('hero_title'),
  heroSubtitle: text('hero_subtitle'),
  categoryImages: jsonb('category_images').$type<Record<string, string>>(),
  sourceUrl: text('source_url'),
  socialLinks: jsonb('social_links').$type<{ facebook?: string; instagram?: string; youtube?: string; tiktok?: string }>(),
  financingUrl: text('financing_url'),
  aboutContent: text('about_content'),
  serviceContent: text('service_content'),
  partsContent: text('parts_content'),
  heroSlides: jsonb('hero_slides').$type<Array<{ image: string; video?: string; title: string; subtitle: string; ctaText?: string; ctaLink?: string }>>(),
  chatWidgetCode: text('chat_widget_code'),
  chatEnabled: boolean('chat_enabled').notNull().default(true),
  chatAgentName: text('chat_agent_name'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
})
